"""
PDF Export — MTM-branded PDF generation from markdown task plans.
Uses markdown-pdf (pure Python, no system dependencies).
"""

import tempfile
from pathlib import Path

from markdown_pdf import MarkdownPdf, Section

# MTM brand CSS
MTM_CSS = """
body {
    font-family: Arial, Helvetica, sans-serif;
    font-size: 11pt;
    line-height: 1.5;
    color: #1a1a1a;
}
h1 {
    color: #1c487b;
    font-size: 22pt;
    border-bottom: 2px solid #0891b2;
    padding-bottom: 6px;
    margin-top: 24px;
}
h2 {
    color: #0e7490;
    font-size: 16pt;
    margin-top: 20px;
}
h3 {
    color: #155e75;
    font-size: 13pt;
    margin-top: 16px;
}
table {
    border-collapse: collapse;
    width: 100%;
    margin: 12px 0;
}
th {
    background-color: #0e7490;
    color: white;
    padding: 8px 12px;
    text-align: left;
    font-size: 10pt;
}
td {
    border: 1px solid #d1d5db;
    padding: 6px 12px;
    font-size: 10pt;
}
tr:nth-child(even) td {
    background-color: #f0fdfa;
}
strong {
    color: #1c487b;
}
ul, ol {
    margin: 8px 0;
}
li {
    margin: 4px 0;
}
"""

APP_DIR = Path(__file__).parent


def generate_pdf(markdown_content: str, goal: str) -> bytes:
    """Generate an MTM-branded PDF from markdown content.

    Args:
        markdown_content: The markdown task plan from the agent.
        goal: The original goal text (used in the title).

    Returns:
        PDF file contents as bytes.
    """
    # Build the full document with logo and title header
    logo_md = f"![MTM Logo]({APP_DIR / 'mtm-logo.png'})\n\n"
    header = (
        f"# Task Plan\n\n"
        f"**Goal:** {goal}\n\n"
        f"---\n\n"
    )
    full_md = logo_md + header + markdown_content

    footer = (
        "\n\n---\n\n"
        "*Generated by the MTM Task Generator Agent — "
        "[mtm.now](https://mtm.now)*"
    )
    full_md += footer

    pdf = MarkdownPdf(toc_level=2)
    pdf.meta["title"] = f"Task Plan: {goal[:80]}"
    pdf.meta["author"] = "Meet the Moment"
    pdf.add_section(Section(full_md, paper_size="Letter"), user_css=MTM_CSS)

    # Save to temp file and read bytes back
    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp:
        tmp_path = tmp.name
    pdf.save(tmp_path)
    pdf_bytes = Path(tmp_path).read_bytes()
    Path(tmp_path).unlink(missing_ok=True)
    return pdf_bytes
